testname: webMUSHRA Example
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: 練習ページ
      content: 本実験では音源方向及び音質のreferenceとの近さを0~100で評価してください．<br>回答は最後に結果の表が出るのでその数値を<a href="https://docs.google.com/forms/d/e/1FAIpQLSefiPM0XE5z7EWudDfDbAqUDLPHz5BWj-L1PSPoESt2UOAxGQ/viewform?usp=sf_link">Googleフォーム</a>に書き写す形でお願いいたします．</p>      
    - type: mushra
      id: trial1
      name: MUSHRA
      content: このページは評価のやり方を練習するサンプルです。referenceと聞き比べて音質に関して近さを0~100で評価してください．またサンプルの中にはreferenceも含まれています．
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
    - 
        
        - type: mushra
          id: 実験1
          name: 実験1
          content: 左側からギター音が聞こえます．音質に関して評価してください。
          enableLooping: true 
          reference: configs/resources/audio/true/guitar/signal_all_left.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/guitar/signal_all_left.wav
              C2: configs/resources/audio/dismics/trans/guitar/signal_all_left.wav
              C3: configs/resources/audio/singlemic/org/guitar/signal_all_left.wav
              C4: configs/resources/audio/singlemic/trans/guitar/signal_all_left.wav    
              C5: configs/resources/audio/anchor/guitar/signal_all_left.wav
        - type: mushra
          id: 実験2
          name: 実験2
          content: 左側からギター音が聞こえます．音の定位感に関して評価してください。
          enableLooping: true 
          reference: configs/resources/audio/true/guitar/signal_all_left.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/guitar/signal_all_left.wav
              C2: configs/resources/audio/dismics/trans/guitar/signal_all_left.wav
              C3: configs/resources/audio/singlemic/org/guitar/signal_all_left.wav
              C4: configs/resources/audio/singlemic/trans/guitar/signal_all_left.wav   
              C5: configs/resources/audio/anchor/guitar/signal_all_left.wav 
        - type: mushra
          id: 実験3
          name: 実験3
          content: 右側からギター音が聞こえます．音質に関して評価してください。
          enableLooping: true 
          reference: configs/resources/audio/true/guitar/signal_all_right.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/guitar/signal_all_right.wav
              C2: configs/resources/audio/dismics/trans/guitar/signal_all_right.wav
              C3: configs/resources/audio/singlemic/org/guitar/signal_all_right.wav
              C4: configs/resources/audio/singlemic/trans/guitar/signal_all_right.wav    
              C5: configs/resources/audio/anchor/guitar/signal_all_right.wav
        - type: mushra
          id: 実験4
          name: 実験4
          content: 右側からギター音が聞こえます．音の定位感に関して評価してください。
          enableLooping: true 
          reference: configs/resources/audio/true/guitar/signal_all_right.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/guitar/signal_all_right.wav
              C2: configs/resources/audio/dismics/trans/guitar/signal_all_right.wav
              C3: configs/resources/audio/singlemic/org/guitar/signal_all_right.wav
              C4: configs/resources/audio/singlemic/trans/guitar/signal_all_right.wav   
              C5: configs/resources/audio/anchor/guitar/signal_all_right.wav   
        - type: mushra
          id: 実験5
          name: 実験5
          content: 左側から音声が聞こえます．音質に関して評価してください。
          enableLooping: true 
          reference: configs/resources/audio/true/male/signal_all_left.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/male/signal_all_left.wav
              C2: configs/resources/audio/dismics/trans/male/signal_all_left.wav
              C3: configs/resources/audio/singlemic/org/male/signal_all_left.wav
              C4: configs/resources/audio/singlemic/trans/male/signal_all_left.wav   
              C5: configs/resources/audio/anchor/male/signal_all_left.wav       
        - type: mushra
          id: 実験6
          name: 実験6
          content: 左側から音声が聞こえます．音の定位感に関して評価してください。
          enableLooping: true 
          reference: configs/resources/audio/true/male/signal_all_left.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/male/signal_all_left.wav
              C2: configs/resources/audio/dismics/trans/male/signal_all_left.wav
              C3: configs/resources/audio/singlemic/org/male/signal_all_left.wav
              C4: configs/resources/audio/singlemic/trans/male/signal_all_left.wav   
              C5: configs/resources/audio/anchor/male/signal_all_left.wav       
        - type: mushra
          id: 実験7
          name: 実験7
          content: 右側から音声が聞こえます．音質に関して評価してください。
          enableLooping: true 
          reference: configs/resources/audio/true/male/signal_all_left.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/male/signal_all_right.wav
              C2: configs/resources/audio/dismics/trans/male/signal_all_right.wav
              C3: configs/resources/audio/singlemic/org/male/signal_all_right.wav
              C4: configs/resources/audio/singlemic/trans/male/signal_all_right.wav   
              C5: configs/resources/audio/anchor/male/signal_all_right.wav       
        - type: mushra
          id: 実験8
          name: 実験8
          content: 右側から音声が聞こえます．音の定位感に関して評価してください。
          enableLooping: true 
          reference: configs/resources/audio/true/male/signal_all_right.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/male/signal_all_right.wav
              C2: configs/resources/audio/dismics/trans/male/signal_all_right.wav
              C3: configs/resources/audio/singlemic/org/male/signal_all_right.wav
              C4: configs/resources/audio/singlemic/trans/male/signal_all_right.wav   
              C5: configs/resources/audio/anchor/male/signal_all_right.wav       

    - type: finish
      name: ボタンを押して結果を表示してください．
      content: 結果を<a href="https://docs.google.com/forms/d/e/1FAIpQLSefiPM0XE5z7EWudDfDbAqUDLPHz5BWj-L1PSPoESt2UOAxGQ/viewform?usp=sf_link">Googleフォーム</a>に入力してください．
      popupcontent: 結果を<a href="https://docs.google.com/forms/d/e/1FAIpQLSefiPM0XE5z7EWudDfDbAqUDLPHz5BWj-L1PSPoESt2UOAxGQ/viewform?usp=sf_link">Googleフォーム</a>に入力してください．    
      showResults: true
      writeResults: true