testname: webMUSHRA Example
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: 練習ページ
      content: 本実験では音源方向及び音質のreferenceとの近さを0~100で評価してください．詳しい内容はサンプルのページに記述してあるのでよく読んでから評価をお願いいたします．      
    - type: mushra
      id: trial1
      name: MUSHRA
      content: このページは評価のやり方を練習するサンプルです．referenceと聞き比べて音の音質や音像位置を0~100で評価してください．またサンプルの中にはreferenceも含まれています．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
    - 
        
        - type: mushra
          id: Experiment 1
          name: Experiment 1
          content: 左側付近からギター音が聞こえます(移動します)．referenceと比較して音像位置や音質が近いかなどを評価してください．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
          enableLooping: true 
          reference: configs/resources/audio/true/guitar/signal_all_left.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/guitar/signal_all_left.wav
              C2: configs/resources/audio/dismics/trans/guitar/signal_all_left.wav
              C3: configs/resources/audio/singlemic/org/guitar/signal_all_left.wav
              C4: configs/resources/audio/singlemic/trans/guitar/signal_all_left.wav    
              C5: configs/resources/audio/anchor_1.6/guitar/signal_all_left.wav
        - type: mushra
          id: Experiment 2
          name: Experiment 2
          content: 前方(左、前、右)付近からギター音が聞こえます(移動します)．referenceと比較して音像位置や音質が近いかなどを評価してください．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
          enableLooping: true 
          reference: configs/resources/audio/true/guitar/signal_all_mid.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/guitar/signal_all_mid.wav
              C2: configs/resources/audio/dismics/trans/guitar/signal_all_mid.wav
              C3: configs/resources/audio/singlemic/org/guitar/signal_all_mid.wav
              C4: configs/resources/audio/singlemic/trans/guitar/signal_all_mid.wav   
              C5: configs/resources/audio/anchor_1.6/guitar/signal_all_mid.wav 
        - type: mushra
          id: Experiment 3
          name: Experiment 3
          content: 右側付近からギター音が聞こえます(移動します)．referenceと比較して音像位置や音質が近いかなどを評価してください．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
          enableLooping: true 
          reference: configs/resources/audio/true/guitar/signal_all_right.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/guitar/signal_all_right.wav
              C2: configs/resources/audio/dismics/trans/guitar/signal_all_right.wav
              C3: configs/resources/audio/singlemic/org/guitar/signal_all_right.wav
              C4: configs/resources/audio/singlemic/trans/guitar/signal_all_right.wav    
              C5: configs/resources/audio/anchor_1.6/guitar/signal_all_right.wav
        - type: mushra
          id: Experiment 4
          name: Experiment 4
          content: 左側付近から音声が聞こえます(移動します)．referenceと比較して音像位置や音質が近いかなどを評価してください．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
          enableLooping: true 
          reference: configs/resources/audio/true/male/signal_all_left.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/male/signal_all_left.wav
              C2: configs/resources/audio/dismics/trans/male/signal_all_left.wav
              C3: configs/resources/audio/singlemic/org/male/signal_all_left.wav
              C4: configs/resources/audio/singlemic/trans/male/signal_all_left.wav   
              C5: configs/resources/audio/anchor_1.6/male/signal_all_left.wav       
        - type: mushra
          id: Experiment 5
          name: Experiment 5
          content: 前方(左、前、右)付近から音声が聞こえます(移動します)．referenceと比較して音像位置や音質が近いかなどを評価してください．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
          enableLooping: true 
          reference: configs/resources/audio/true/male/signal_all_mid.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/male/signal_all_mid.wav
              C2: configs/resources/audio/dismics/trans/male/signal_all_mid.wav
              C3: configs/resources/audio/singlemic/org/male/signal_all_mid.wav
              C4: configs/resources/audio/singlemic/trans/male/signal_all_mid.wav   
              C5: configs/resources/audio/anchor_1.6/male/signal_all_mid.wav       
        - type: mushra
          id: Experiment 6
          name: Experiment 6
          content: 右側付近から音声が聞こえます(移動します)．referenceと比較して音像位置や音質が近いかなどを評価してください．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
          enableLooping: true 
          reference: configs/resources/audio/true/male/signal_all_right.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/male/signal_all_right.wav
              C2: configs/resources/audio/dismics/trans/male/signal_all_right.wav
              C3: configs/resources/audio/singlemic/org/male/signal_all_right.wav
              C4: configs/resources/audio/singlemic/trans/male/signal_all_right.wav   
              C5: configs/resources/audio/anchor_1.6/male/signal_all_right.wav       
        - type: mushra
          id: Experiment 7
          name: Experiment 7
          content: 左側付近から音声が聞こえます(移動します)．referenceと比較して音像位置や音質が近いかなどを評価してください．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
          enableLooping: true 
          reference: configs/resources/audio/true/female/signal_all_left.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/female/signal_all_left.wav
              C2: configs/resources/audio/dismics/trans/female/signal_all_left.wav
              C3: configs/resources/audio/singlemic/org/female/signal_all_left.wav
              C4: configs/resources/audio/singlemic/trans/female/signal_all_left.wav   
              C5: configs/resources/audio/anchor_1.6/female/signal_all_left.wav       
        - type: mushra
          id: Experiment 8
          name: Experiment 8
          content: 前方(左、前、右)付近から音声が聞こえます(移動します)．referenceと比較して音像位置や音質が近いかなどを評価してください．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
          enableLooping: true 
          reference: configs/resources/audio/true/female/signal_all_mid.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/female/signal_all_mid.wav
              C2: configs/resources/audio/dismics/trans/female/signal_all_mid.wav
              C3: configs/resources/audio/singlemic/org/female/signal_all_mid.wav
              C4: configs/resources/audio/singlemic/trans/female/signal_all_mid.wav   
              C5: configs/resources/audio/anchor_1.6/female/signal_all_mid.wav       
        - type: mushra
          id: Experiment 9
          name: Experiment 9
          content: 右側付近から音声が聞こえます(移動します)．referenceと比較して音像位置や音質が近いかなどを評価してください．一番良いものは100点をつけ、一番悪いと思うものは40点以下の点をつけてください．またなるべく同じ点数はつけないようにしてください．(差がないと感じたら同点で構いません)．
          enableLooping: true 
          reference: configs/resources/audio/true/female/signal_all_right.wav
          createAnchor35: false
          createAnchor70: false
          stimuli:
              C1: configs/resources/audio/dismics/org/female/signal_all_right.wav
              C2: configs/resources/audio/dismics/trans/female/signal_all_right.wav
              C3: configs/resources/audio/singlemic/org/female/signal_all_right.wav
              C4: configs/resources/audio/singlemic/trans/female/signal_all_right.wav   
              C5: configs/resources/audio/anchor_1.6/female/signal_all_right.wav     
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: name(English)
            name: name
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
      